baseURL = 'http://DPKamalnayan/SoftwareEngineer.github.io/'
languageCode = 'en-us'
title = 'SoftwareEngineer'
theme = 'anatole'
[params]
title = "I'm Kamalnayan"
author = "Kamalnayan"
description = "Call me Nayan"
profilePicture = "images/MarlinMason.jpeg"
