baseURL = 'http://dpkamalnayan.github.io/SoftwareEngineer.github.io/'
languageCode = 'en'
title = 'SoftwareEngineer'
theme = 'anatole'
[params]
title = "Nayan"
author = "Kamalnayan"
description = """blogging form Chandigarh
"""
profilePicture = "images/MarlinMason.jpeg"
mainSections = ["posts"]
disableThemeSwitcher = true 
[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://in.linkedin.com/in/d-p-kamalnayan-48ba73255"

[[params.socialIcons]]
icon = "fab fa-github"
title = "Github"
url = "https://github.com/DPKamalnayan"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:nayanlamak.rm+website@gmail.com"

[menu]
[[menu.main]]
 name = "Home"
 identifier = "home"
 weight = 100
 url = "/"

[[menu.main]]
 name = "Portfolio"
 weight = 200
 identifier = "portfolio"
 url = "/portfolio/"

[[menu.main]]
 name = "Posts"
 weight = 200
 identifier = "posts"
 url = "/posts/"

[[menu.main]]
 name = "About"
 weight = 400
 identifier = "about"
 url = "/about/"

#[[menu.main]]
 #name = "Accomplishments"
 #weight = 500
 #identifier = "accomplishments"

#[[menu.main]]
 #name = "Awards"
# weight = 510
# identifier = "awards"
# url = "/awards/"
# parent = "accomplishments"  

[[menu.main]]
 name = "Certifications"
 weight = 520
 identifier = "certifications"
 url = "/certifications/"
# parent = "accomplishments"

[[menu.main]]
 name = "Contact"
 weight = 600
 identifier = "contact"
 url = "/contact/"

[[menu.footer]]
 name = "imprint"
 weight = 1
 identifier = "imprint"
 url = "/imprint/"

